# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71055d5f6166a06d1513a83929dd0a96a457802eaf190060f960dac1143a292c1c1fbd66f18bd140aabb6677b8cef9f2804dc5da5ce63df7a5cae2f555f39929

test:
  secret_key_base: 014db178a9b211922adccd97836970d4eb49b794666e1d8b3118cc58236196a365bd0f75d84119fb97b90acbc851899d420369ead710b8990a72a699424b6ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
